### ISSUE TITLE
Livestock

### ISSUE THREAD

**Issue by P0Pss** [nsporillo/GlobalWarming#27]
Livestock producing greenhouse gases, primarily Cows and Sheep.
Instead of using total cows and sheep maybe you could check how close they are to various blocks which dont spawn naturally, such as fences, gates, planks etc. Would give the players a chance to not keep to many animals or have a shared livestock?

**Comment by nsporillo** [comment]
There are many different ways we could track livestock versus free roaming animals in game. The best way would be to listen for the event corresponding to a entity spawn and check if the cause was due to breeding. Furthermore, we could try to listen for interaction events between players and mobs to detect taming (for mobs that can be tamed).

I like this idea and it'd be an interesting addition. Thank you.

**Comment by nsporillo** [comment]
This has been added. Thank you @P0Pss
