### ISSUE TITLE
Implement Sea Level Rise Mechanics

### ISSUE THREAD

**Issue by tbredin** [nsporillo/GlobalWarming#4]
Ice should melt and sea levels should rise accoringly, if CO2 levels rise  above a certain limit (1 or 2 degrees, perhaps?)

**Comment by tbredin** [comment]
Perhaps also integration mass migration of villagers whose villages end up underwater?

**Comment by nsporillo** [comment]
Yes, the readme has a sample model for the types of effects and at what temperatures. They will be configurable, and we plan to have our default model resemble reality as best we can.

Regarding migration of villagers, it might be too expensive of an mechanics change to make through the bukkit api. I think it'd be possible to modify the path finding code of the CraftVillager object, but at this time outside of the immediate scope of the project.

**Comment by nsporillo** [comment]
Updated this issue to correspond to a deliverable. Added to our planning board.

**Comment by nsporillo** [comment]
The mechanic is now testable in game.

**Comment by piash2004** [comment]
How can I contribute? Clone, fork, pull, commit- I'm novice in all of these, but I live in Bangladesh,  a country suffering due to climate change.

**Comment by nsporillo** [comment]
@piash2004 by downloading and running the plugin on a server with some friends, so that after some time spent playing the game with the plugin installed you can identify areas for improvement or report bugs. 

Spreading the word is good too, I plan on continuing to support and add features to the plugin time permitted. Having a community of people invested in the future development of the plugin is important to me 👍
