### ISSUE TITLE
Carbon effects occuring when carbon footprint is negative in MC 1.15.1 GW 1.2.3

### ISSUE THREAD

**Issue by wilbowma** [nsporillo/GlobalWarming#45]
**Describe the bug**
I'm getting a lot of skeleton horses spawning in place of passive mobs, despite the temperature being at or below 14C. This happens for both mobs found in the wild and farms.

The issue seems to be reproducible simply by breeding pigs until one pops out a skeleton horse.

**To Reproduce**
1. Keep a negative carbon footprint.
2. Breed pigs.
3. One will spawn as a skeleton horse.

**Expected behavior**
Skeleton horses should not spawn until carbon emissions elevate temperature above the target range of 14C.

**Screenshots**
![2019-12-29_00 43 32](https://user-images.githubusercontent.com/1133598/71554536-58095180-29d5-11ea-8ada-3fdb63fc2ea1.png)

**Additional context**

I'm running Minecraft 1.15.1 and GW v1.2.3. I'm using default configuration.
I'm using Paper 1.15.1 29 (https://github.com/PaperMC/Paper/commit/9205b75c86c5bd52af5ac642de1326c8572909a6)

**Comment by nsporillo** [comment]
- You can go to `plugins/GlobalWarming/models/world/entityFitnessModel.json`
- Search for `SKELETON_HORSE` and adjust the fitness at associated temps as desired
- `SKELETON_HORSE` spawns are caused by the alternate property in the model file
- Fitness is another word for "probability this mob will spawn when it should" So for chickens, cows, etc we say at around 14C there is 100% chance a cow will spawn when it is supposed to spawn
- However you can observe that even at 13.86C there is an non-zero chance that those spawns for cows,chickens,etc will be replaced with skeleton horse
- You can set `alternate` to `""` to disable that behavior
