### ISSUE TITLE
Implement Biodiversity Loss Mechanics

### ISSUE THREAD

**Issue by tbredin** [nsporillo/GlobalWarming#6]
Unsure on the best way to implement this but how do we represent mass extinction related to loss of biodiversity?

**Comment by nsporillo** [comment]
We can consider each mob on a case by case basis, using the model file to determine the temperature range for survival of each mob. 

Consider the following slide regarding ecological niches:
![image](https://user-images.githubusercontent.com/1480197/44376209-6da76680-a4c5-11e8-8e1b-e72e15289ce1.png)

- As the temperature inches further from the ideal range for a given species, their fitness decreases. At some point, they wont reproduce - and eventually the temperature will be too extreme and they will die. 

I would say that the mechanics for wiping out species is well defined, in that we just cancel their spawn events once temperature is too high and eventually when chunks load we scan the chunks entities and wipe out remaining mobs, perhaps with a probability function supplied by the model input.

**Comment by fega** [comment]
Hello, keep in mind that in theory the biodiversity have the hability to adapt (slowly to the environment changes)

**Comment by nsporillo** [comment]
@fega Yeah I think that'd be an interesting concept to explore further. If some entities which perhaps should have been wiped out stay dormant in a unloaded chunk for a while (or if the chunk is loaded a few times, but we apply probability for the chance of death and they manage to survive) then we could mark them as adapted or something. If you'd like to develop the idea further, feel free to open a new issue - I left this open to allow for more discussion, but since your suggestion is a little different I wont edit the parent.

**Comment by nsporillo** [comment]
These changes are present in the latest release!
